#define IDS_APP_TITLE 1
#define IDS_TOOLTIP 2

#define IDM_EXIT 100
#define IDM_RELOAD_CONFIG 102

#define IDI_NOTIFICATION_ICON 200

#define IDC_CONTEXT_MENU 300
#define IDC_ABOUT_TEXT 302
#define IDC_ABOUT_GITHUB 304

#define IDD_ABOUT 400
